// SOME ACTIONS
const FETCH_POSTS = 'FETCH_POSTS';
const CREATE_POST = 'CREATE_POST';
const DELETE_POST = 'DELETE_POST';
const FETCH_POST_ID = 'FETCH_POST_ID';

export {
  FETCH_POSTS,
  CREATE_POST,
  DELETE_POST,
  FETCH_POST_ID
};